# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xfce-pvc
  namespace: desktop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard