# xfce-desktop.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xfce-desktop
  namespace: desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xfce-desktop
  template:
    metadata:
      labels:
        app: xfce-desktop
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio if not needed
    spec:
      securityContext:  # Add pod-level security context
        runAsUser: 1000  # Use a non-root user (adjust to match your image)
        runAsGroup: 1000
        fsGroup: 1000 
      containers:
      - name: xfce
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "2"
        #securityContext:
        #  capabilities:
        #    add: ["SYS_RESOURCE"]  # Allow OOM score adjustments
        #  privileged: false
        # image: kasmweb/ubuntu-xfce:1.14.0  # Tested image
        env:
          - name: VNC_PW
            valueFrom:
              secretKeyRef:
                name: vnc-secret
                key: password
        image: europe-west3-docker.pkg.dev/platform-app-ilx/docker-image-repository/xfce-chromium:latest
        # command: ["/bin/sh", "-c"]
        volumeMounts:
        - name: vnc-password
          mountPath: /etc/vnc-secret
          readOnly: true
        - name: user-data
          mountPath: /home/developer
        ports:
        - containerPort: 5901
      volumes:
      - name: vnc-password
        secret:
          secretName: vnc-secret
      - name: user-data
        persistentVolumeClaim:
          claimName: xfce-pvc
          readOnly: false